### ISSUE TITLE
Change the name of the payum-exemple extensions

### ISSUE THREAD

**Issue by PyRowMan** [Combodo/CombodoPayumStripe#10]
Maybe the classes should be named differently than the ones in the sylius example?
Or it may be mentioned that they are the same?

_Originally posted by @bruno-ds in https://github.com/Combodo/CombodoPayumStripe/pull/9_

**Comment by bruno-ds** [comment]
if they are the same maybe we could have a `/doc/examples-common` directory where they are stored?

**Comment by PyRowMan** [comment]
Actually i'm thinking that the `payum-exemple` should be named `symfony-example` because payum is not dependent to symfony; therefore your `common-examples` directory could be named `payum-example` ?

**Comment by bruno-ds** [comment]
I agree about `symfony-example`,
for `payum-example`, well it remain quite dependent to symfony, for example using yii or laravel, I don't know if you'll be able to use the code contained in this dir.

This considered, maybe the code shared between raw symfony and sylius should be stored under the  `symfony-example` directory?

**Comment by PyRowMan** [comment]
Not actually all the extensions; 

For example this extension can be used without symfony : https://github.com/Combodo/CombodoPayumStripe/blob/master/doc/payum-example/src/AppBundle/Payment/StripeV3RequirementsFulfillerOnCaptureExtensions.php


Oh well actually you are right ! To be fair something like that would be the best I suppose : 

`/doc/examples/symfony-examples/raw-examples`
`/doc/examples/symfony-examples/sylius-examples`
`/doc/examples/payum-examples`

**Comment by PyRowMan** [comment]
Hi @bruno-ds 
Here is the future PR, will you have the time to take a little look ?

https://github.com/Combodo/CombodoPayumStripe/compare/master...PyRowMan:tree-examples-folder?expand=1

**Comment by bruno-ds** [comment]
Sorry,
I'm In a urge, this will last for a couple of days,
Sorry, I promise that I'll look into it ASAP!
