### ISSUE TITLE
Is it usefull to repeat the whole readme?

### ISSUE THREAD

**Issue by PyRowMan** [Combodo/CombodoPayumStripe#11]
I was thinking the best thing to do where to define that there is two types of examples in the main readme, and then point to two others readme in each example that would explain their specifications.

_Originally posted by @bruno-ds in https://github.com/Combodo/CombodoPayumStripe/pull/9_

**Comment by bruno-ds** [comment]
I agree,
I would just like to try to let some content in the root doc. directory to avoid the necessity to update two files if something changes (I'm not really trustworthy when it come to this kind of things)

**Comment by PyRowMan** [comment]
Yeah, that would be great to have a tree-ish documentation; It's easier to maintain.

**Comment by bruno-ds** [comment]
done with b0a3fcd34ad726ded23c442a430ba86bf1d29514
