### ISSUE TITLE
There is no need of a webhook

### ISSUE THREAD

**Issue by PyRowMan** [Combodo/CombodoPayumStripe#2]
As I can see in the code you have given directly the 'done' route to stripe; by doing that, once the payment is done, he doesn't go back through your gateway.

Here is the original way : 
```php
// src/Action/Api/ObtainTokenAction.php
private function obtainSession(ObtainToken $request, ArrayObject $model): Session
{
    Stripe::setApiKey($this->keys->getSecretKey());
    $session = Session::create(
        [
            'success_url'           => $request->getToken()->getAfterUrl(),
            'cancel_url'            => $request->getToken()->getAfterUrl(),
            'payment_method_types'  => ['card'],
            'submit_type'           => Session::SUBMIT_TYPE_PAY,
            'line_items'            => $model['line_items'],
            'payment_intent_data'   => [
                'metadata'              => $model['metadata'] ?? ['payment_id' => $model['id']],
            ],
            'client_reference_id'   => $request->getToken()->getHash(),
        ]
    );

    return $session;
}
```

By using the `$request->getToken()->getTargetUrl()` method you can get the capture url in order to send the user to this route after the payment.

Here is how I propose to do :
```php
// src/Action/Api/ObtainTokenAction.php
private function obtainSession(ObtainToken $request, ArrayObject $model): Session
{
    Stripe::setApiKey($this->keys->getSecretKey());
    $session = Session::create(
        [
            'success_url'           => $request->getToken()->getTargetUrl() . '?status=success',
            'cancel_url'            => $request->getToken()->getTargetUrl() . '?status=canceled',
            'payment_method_types'  => ['card'],
            'submit_type'           => Session::SUBMIT_TYPE_PAY,
            'line_items'            => $model['line_items'],
            'payment_intent_data'   => [
                'metadata'              => $model['metadata'] ?? ['payment_id' => $model['id']],
            ],
            'client_reference_id'   => $request->getToken()->getHash(),
        ]
    );

    return $session;
}
```

```php
// src/Action/CaptureAction.php
public function execute($request)
{
    RequestNotSupportedException::assertSupports($this, $request);
    $model = ArrayObject::ensureArrayObject($request->getModel());
    $getHttpRequest = new GetHttpRequest();
    $this->gateway->execute($getHttpRequest);
    if ($getHttpRequest->method == 'GET' && isset($getHttpRequest->query['status'])) {
        // @TODO Check payment status
        return;
    }

    if ($model['status']) {
        return;
    }

    if ($model['customer']) {
        return;
    }

    $obtainToken = new ObtainToken($request->getToken());
    $obtainToken->setModel($model);

    $this->gateway->execute($obtainToken);
}
```

**Comment by bruno-ds** [comment]
Thank you, 
There are currently two way to verify that a payment succeeded: 
 - NotifyUnsafeAction that should be called by a webhook
 - HandleLostPaymentsAction that should be integrated into a CLI command and be run within a cron

I was planning to add a third way: 
 - on the customer landing back to the store, after the payment (in case of a connection error, and in order to not have to wait for the cron)

I think that your solution is elegant, I will soon look into it.

**BUT**, personally, I consider the webhook as mandatory because (of the murphy's law) there are plenty of cases where the customer could not land the the success page.

(trust me several years ago I had to integrate a payment solution that did not provide webhook, it was a disaster!)

**Comment by PyRowMan** [comment]
Hi @bruno-ds, 

I think that all of theses methods can be used together; however you should consider the fact that adding a webhook to the stripe dashboard may be impossible for some (like myself). 

Therefore in my case there is only two available solutions : 
- Checking the payments status with a cron or a daemon .
- Redirect the user to a route where the payment status will be checked.

Both of the solutions **should** actually be used in theses cases.


I'm currently working on theses changes in my fork.
